import { Inter } from "next/font/google";
import "./globals.css";
import Link  from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Morrocolabs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Menudata = [
    { name: "About us", link: "" },
    { name: "vision statment", link: "" },
    { name: "key aspects", link: "" },
    { name: "The social innovation initiatives ", link: "" },
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header */}
        <header className=" flex justify-around items-center">
         <div className="img ">
              <img src="./images/Logo.png" alt="" className=" w-24" />
            </div>  
            <div className=" text-white/50 text-center items-center space-x-6 ">
           
            {Menudata.map( (item) => (
                <Link href={item.link}>{item.name}</Link>
            ))}
          </div>
        </header>
        {/* end header */}

        {children}
      </body>
    </html>
  );
}
